spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&setTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
